# Standard library information used by the traceback module for more informative
# ModuleNotFound error messages.
# Generated by check_extension_modules.py

_MISSING_STDLIB_MODULE_MESSAGES = {'_ctypes_test': "Standard library module disabled during build '_ctypes_test' "
                 'was not found',
 '_overlapped': 'Unsupported platform for Windows-only standard library module '
                "'_overlapped'",
 '_scproxy': "Unsupported platform for standard library module '_scproxy'",
 '_testbuffer': "Standard library module disabled during build '_testbuffer' "
                'was not found',
 '_testcapi': "Standard library module disabled during build '_testcapi' was "
              'not found',
 '_testclinic': "Standard library module disabled during build '_testclinic' "
                'was not found',
 '_testclinic_limited': 'Standard library module disabled during build '
                        "'_testclinic_limited' was not found",
 '_testconsole': 'Unsupported platform for Windows-only standard library '
                 "module '_testconsole'",
 '_testimportmultiple': 'Standard library module disabled during build '
                        "'_testimportmultiple' was not found",
 '_testinternalcapi': 'Standard library module disabled during build '
                      "'_testinternalcapi' was not found",
 '_testlimitedcapi': 'Standard library module disabled during build '
                     "'_testlimitedcapi' was not found",
 '_testmultiphase': 'Standard library module disabled during build '
                    "'_testmultiphase' was not found",
 '_testsinglephase': 'Standard library module disabled during build '
                     "'_testsinglephase' was not found",
 '_winapi': 'Unsupported platform for Windows-only standard library module '
            "'_winapi'",
 '_wmi': "Unsupported platform for Windows-only standard library module '_wmi'",
 '_xxtestfuzz': "Standard library module disabled during build '_xxtestfuzz' "
                'was not found',
 'msvcrt': 'Unsupported platform for Windows-only standard library module '
           "'msvcrt'",
 'nt': "Unsupported platform for Windows-only standard library module 'nt'",
 'winreg': 'Unsupported platform for Windows-only standard library module '
           "'winreg'",
 'winsound': 'Unsupported platform for Windows-only standard library module '
             "'winsound'",
 'xxlimited': "Standard library module disabled during build 'xxlimited' was "
              'not found',
 'xxlimited_35': "Standard library module disabled during build 'xxlimited_35' "
                 'was not found',
 'xxsubtype': "Standard library module disabled during build 'xxsubtype' was "
              'not found'}
